name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
          
      -
        name: Remove previous Docker image
        run: |
          docker pull "${{ secrets.DOCKERHUB_USERNAME }}/car_pose_recognition:latest" || true
          docker image rm "${{ secrets.DOCKERHUB_USERNAME }}/car_pose_recognition:latest" || true
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/car_pose_recognition:latest

      -
        name: Save build log to a file
        run: |
          # Capture build output to a log file
          docker build -t my_image . > build.log 2>&1 || true



      
      - 
        name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NOTIFICATION_EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Workflow Build Failed
          body:  |
            The workflow build has failed .
             Details:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}
            - Workflow Run ID: ${{ github.run_id }}
            Please check the build logs for more details.
            
            
          from: ${{ secrets.NOTIFICATION_EMAIL }}
          to: ${{ secrets.NOTIFICATION_EMAIL }} 
          attachments: |
            build.log
            

      -
        name: Send email on success
        if: success()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NOTIFICATION_EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Workflow Build Succeeded
          body: |
            The workflow build for the repository on GitHub has successfully completed.
            Details:
            - Repository: ${{ github.repository }}
            - Branch: ${{ github.ref }}
            - Commit: ${{ github.sha }}
            - Workflow Run ID: ${{ github.run_id }}
            The build is successful, and you can proceed with any necessary deployment steps.
          from: ${{ secrets.NOTIFICATION_EMAIL }}
          to: ${{ secrets.NOTIFICATION_EMAIL }} 
