name: ci

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/car_pose_recognition:latest


      - 
        name: Notify on failure
        if: failure()
        uses: softprops/action-gh-pages@v0.6.0
        with:
          branch: failure-email-notification
          build_dir: "failure-email-notification"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Workflow failed"
          pusher: ${{ github.actor }}
          recipient_email: ${{ secrets.NOTIFICATION_EMAIL }}    

    
